# Generated by Django 3.2.11 on 2022-03-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotusapp', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='name1',
        ),
    ]
